# Alternative deployment config for Render.com
# If DigitalOcean isn't working, we can use this
services:
  - type: web
    name: tellyousomeday-fullstack
    env: node
    plan: free
    repo: https://github.com/dusharakalubowila/tellyousomeday
    branch: main
    buildCommand: |
      npm ci
      npm run build
      cd backend
      npm ci --only=production
      cd ..
    startCommand: node backend/server-with-static.js
    healthCheckPath: /api/health
    port: 8080
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: MONGODB_URI
        value: mongodb+srv://tellyousomeday-admin:Dkk%40320909@tellyousomeday-cluster.8j0bf4b.mongodb.net/tellyousomeday?retryWrites=true&w=majority&appName=tellyousomeday-cluster
      - key: JWT_SECRET
        value: tellyousomeday-super-secret-jwt-key-production-2025
      - key: FRONTEND_URL
        value: "*"
