# DigitalOcean App Platform Configuration for TellYouSomeday Frontend
name: tellyousomeday
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: dusharakalubowila/tellyousomeday
    branch: main
  build_command: npm ci && npm run build
  output_dir: /dist
  index_document: index.html
  error_document: index.html
  envs:
  - key: VITE_API_URL
    value: https://tellyousomeday-api-xxxxx.ondigitalocean.app/api
